### PR TITLE
rebasing patches for go1.21

### PR DESCRIPTION
**Pull request by phirework**
Steps: 

1. `git checkout tailscale.go1.20 -- .github`, `git commit` #47
2. `git cherry-pick 8c9eff4`, resolve conflict #48
3. `git cherry-pick 6a17f14`, resolve conflict (ignored `26292c0` because changes were already included in step 1) #49
4. `git cherry-pick a2f29de`, resolve conflict #52
5. `git cherry-pick 13373ca` #55
6. `git cherry-pick fb11c0d` and `git cherry-pick db4dc90` #58

### CODE REVIEW

**Comment by bradfitz** [comment]
Can you fix the commit messages to not say `[tailscale1.20]` in them? Just `[tailscale]` is fine if we want to stop updating the number, as it appears the latest style (in the net patches) is.

**Comment by bradfitz** [comment]
`git rebase -i` is my preferred tool for the job there, but you might have a different favorite workflow.

**Comment by bradfitz** [comment]
Otherwise looks good, thanks!

**Comment by phirework** [comment]
@bradfitz done

**Review by bradfitz — APPROVED** [review]

**Pull request merged**
