### PR TITLE
sync: add Assert(R)Locked

### PR DESCRIPTION
**Pull request by josharian**
So we can use it internally.

### CODE REVIEW

**Comment by josharian** [comment]
Oops. Wrong head. Do not merge. You can review https://github.com/tailscale/go/pull/9/commits/143c342b067f407c447818f65074842e8393c841 and leave comments here, though...

**Comment by bradfitz** [comment]
I don't want to add API in our tailscale/go fork. I think we should be able to add this in a separate package. gVisor already did, for instance. We can add tests that check the shape of the underlying sync.Mutex unexported fields and fail in the future if/when we upgrade Go and their innards change.

**Comment by josharian** [comment]
OK. Migrated to https://github.com/tailscale/tailscale/pull/744.

> gVisor already did, for instance.

I just looked and didn't find this. Oh well. I was hoping to just cross-reference my implementation, because it's subtle code.

**Comment by bradfitz** [comment]
> I just looked and didn't find this. Oh well. I was hoping to just cross-reference my implementation, because it's subtle code.

e.g. https://github.com/google/gvisor/blob/go/pkg/sync/mutex_unsafe.go and other files in that package: https://pkg.go.dev/gvisor.dev/gvisor/pkg/sync?tab=doc

**Pull request closed without merging**
