### PR TITLE
Go 1.19.4

### PR DESCRIPTION
**Pull request by andrew-d**
For the security updates listed in https://groups.google.com/g/golang-dev/c/G9Jj4cO4Gpk/m/kOkLVG6TAgAJ

I ran:
```shell
$ git checkout tailscale.go1.19
$ git checkout -b andrew/go1.19.4
$ git merge dc04f3ba1f25313bc9c97e728620206c235db9ee # this is the go1.19.4 tag
```

### CODE REVIEW

**Comment by bradfitz** [comment]
Normally I do something like git fetch git@github.com:golang/go go1.19.4 && git merge FETCH_HEAD, IIRC.

**Comment by bradfitz** [comment]
I haven't looked yet but was this done with a merge or a bunch of cherry-picks? I'd prefer a merge.

**Comment by andrew-d** [comment]
@bradfitz - I ran:
```
$ git checkout tailscale.go1.19
$ git checkout -b andrew/go1.19.4-merge
$ git fetch git@github.com:golang/go go1.19.4 && git merge FETCH_HEAD
```

And got: https://github.com/tailscale/go/compare/tailscale.go1.19...tailscale:go:andrew/go1.19.4-merge

Thoughts?

**Comment by bradfitz** [comment]
Looks right? Push that to this branch?

**Comment by andrew-d** [comment]
Done

**Review by bradfitz — APPROVED** [review]
LGTM once CI's happy

**Review by dsnet — APPROVED** [review]

**Pull request merged**
