### PR TITLE
all: update to Go 1.17.7 point release

### PR DESCRIPTION
**Pull request by josharian**
- [release-branch.go1.17] net/http/internal/testcert: use FIPS-compliant certificate
- [release-branch.go1.17] math/big: prevent overflow in (*Rat).SetString
- [release-branch.go1.17] debug/pe,debug/macho: add support for DWARF5 sections
- [release-branch.go1.17] cmd/go: remove mercurial from bitbucket vcs options
- [release-branch.go1.17] cmd/internal/obj/x86: modify the threshold of assert loop for span6
- [release-branch.go1.17] cmd/compile: don't elide extension for LoadReg to FP register on MIPS64
- [release-branch.go1.17] cmd/compile: remove incorrect arm,arm64 CMP->CMN transformations
- [release-branch.go1.17] cmd/go/internal/modfetch: do not short-circuit canonical versions
- [release-branch.go1.17] crypto/elliptic: make IsOnCurve return false for invalid field elements
- [release-branch.go1.17] cmd/link: force eager binding when using plugins on darwin
- [release-branch.go1.17] runtime: set vdsoSP to caller's SP consistently
- [release-branch.go1.17] go1.17.7
- [release-branch.go1.17] crypto/x509: support NumericString in DN components

This PR will be imported into Gerrit with the title and first
comment (this text) used to generate the subject and body of
the Gerrit change.

**Please ensure you adhere to every item in this list.**

More info can be found at https://github.com/golang/go/wiki/CommitMessage

+ The PR title is formatted as follows: `net/http: frob the quux before blarfing`
  + The package name goes before the colon
  + The part after the colon uses the verb tense + phrase that completes the blank in,
    "This change modifies Go to ___________"
  + Lowercase verb after the colon
  + No trailing period
  + Keep the title as short as possible. ideally under 76 characters or shorter
+ No Markdown
+ The first PR comment (this one) is wrapped at 76 characters, unless it's
  really needed (ASCII art, table, or long link)
+ If there is a corresponding issue, add either `Fixes #1234` or `Updates #1234`
  (the latter if this is not a complete fix) to this comment
+ If referring to a repo other than `golang/go` you can use the
  `owner/repo#issue_number` syntax: `Fixes golang/tools#1234`
+ We do not use Signed-off-by lines in Go. Please don't add them.
  Our Gerrit server & GitHub bots enforce CLA compliance instead.
+ Delete these instructions once you have read and applied them

### CODE REVIEW

**Comment by josharian** [comment]
Straightforward merge update.

**Comment by josharian** [comment]
Don't review yet. After this, I see new test failures in crypto/elliptic. Haven't investigated yet.

**Review by bradfitz — APPROVED** [review]
LGTM after the update to use Go master's crypto/elliptic.

**Comment by josharian** [comment]
This got a bit ugly, but with a few more cherry-picks and tweaks, I got the CI passing. I'm not inclined to do any extra tidying, since this'll all go away when we update our fork to the Go 1.18 release.

PTAL, @bradfitz or @danderson.

**Review by bradfitz — APPROVED** [review]

**Pull request merged**
