### PR TITLE
devendor x/net

### PR DESCRIPTION
**Pull request by crawshaw**
Had to hack at cmd/go to get all.bash passing.

cc @dshynkev

### CODE REVIEW

**Comment by crawshaw** [comment]
anyone: if the iOS binary size is blocking you feel free to take this over while australia is in night. I'm moving slowly and don't know when tomorrow I'll get back to this.

**Comment by crawshaw** [comment]
ping. anyone? better ideas?

**Comment by dshynkev** [comment]
This seems like a good solution to me, as having duplicate symbols just feels inelegant, even if we pruned the non-vendored copy significantly. Of course, I'll defer to @bradfitz.

**Comment by bradfitz** [comment]
I missed any background discussions on this. Why? But this also seems not safe and more diff weight than I want to carry in our tree. It'd make rebasing harder. But mostly I don't see how it helps?

**Comment by bradfitz** [comment]
Nevermind I see the commit message now. (still getting used to PR vs commit message). But this seems like it'll get confusing if we use x/net for other stuff other than dnsmessage, which we do outside of iOS. We won't get the code go.mod specifies. We'll get whatever our go tree has. I'd rather let go.mod force updating what Go's std uses.

**Comment by bradfitz** [comment]
iOS is in pretty great shape now; closing this for now.

**Pull request closed without merging**
