### PR TITLE
[tailscale.go1.19] sync: add metrics

### PR DESCRIPTION
**Pull request by bradfitz**

### CODE REVIEW

**Review by crawshaw — APPROVED** [review]
That’s fine, but when you write code that uses it could you find a way to make it still build with a stock Go? I periodically build tailcontrol locally with my usual goroot to try things out.

**Review by maisem — APPROVED** [review]

**Comment by bradfitz** [comment]
> That’s fine, but when you write code that uses it could you find a way to make it still build with a stock Go? I periodically build tailcontrol locally with my usual goroot to try things out.

Same. I'll build tag the varz export.

**Review by crawshaw — APPROVED** [review]
Looks like it would work.

Note that under many-core heavy contention, this would make the contention worse by causing a stack of cores to fight over the cache line for the varz. Ideally in that case we'd be using per-P varz and adding them on collection.

However given our current total core count is low, I think this is fine.

**Review by maisem — APPROVED** [review]

**Comment by maisem** [comment]
Would this have any negative impact on clients?

**Comment by bradfitz** [comment]
> Would this have any negative impact on clients?

Should be tiny. If you're already in the slow path, another atomic increment (you've already done one) shouldn't hurt compared to what you're about to do to wait.

**Pull request merged**
